# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ManyToManyField(related_name='friends', to='python_belt.User'),
        ),
    ]
