# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0002_quotes_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='favorite',
        ),
        migrations.AddField(
            model_name='quotes',
            name='favorite',
            field=models.ManyToManyField(related_name='favorites', to='python_belt.User'),
        ),
    ]
