# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0002_auto_20170426_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='python_belt.User'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ManyToManyField(related_name='frien', to='python_belt.User'),
        ),
    ]
